let suggestions = [
  "Amazon",
  "Amazon Prime",
  "Airbnb",
  "Aol Mail",
  "American Express",
  "Aol",
  "ABC News",
  "abc",
  "AbeBooks",
  "academy",
  "activision",
  "Advance Auto Parts",
  "Adobe Inc.",
  "Adidas",
  "ad blocker",
  "Africa",
  "Agoda",
  "age calculator",
  "America's Got Talent",
  "Bank of America",
  "Best Buy",
  "Bing",
  "bluestacks",
  "Costco",
  "chat gpt",
  "CNN",
  "Chase bank",
  "capital one",
  "calculator",
  "discord",
  "disney plus",
  "domino's pizza",
  "DuckDuckGo",
  "dropbox",
  "eBay",
  "ESPN",
  "Expedia",
  "email",
  "Epic Games",
  "Facebook",
  "Fox News",
  "facebook log in to facebook",
  "Frontier Airlines",
  "Fortnite",
  "Family Dollar",
  "Fanatics, Inc.",
  "fb lite",
  "The Home Depot",
  "Hotmail",
  "Hulu",
  "Hobby Lobby",
  "HSN",
  "happy birthday",
  "harry potter",
  "Instagram",
  "Indeed",
  "IKEA",
  "iCloud",
  "Instacart",
  "JCPenney",
  "JetBlue",
  "jpg to pdf",
  "Joe Biden",
  "Kahoot!",
  "Kroger",
  "Kayak (company)",
  "Google",
  "Gmail",
  "Google Translate",
  "Google Scholar",
  "Google Drive",
  "MSN",
  "MapQuest",
  "Menards",
  "Minecraft",
  "Mail (Windows)",
  "messenger",
  "Microsoft Teams",
  "microsoft word",
  "Southwest Airlines",
  "Spotify",
  "Shein",
  "steam",
  "speed test",
  "Shopee",
  "stapless",
  "snapchat",
  "Snake",
  "snapfish",
  "sniffies",
  "Startpage",
  "YouTube",
  "Yahoo!",
  "yt",
  "Yahoo! Mail",
  "YouTube Music",
  "y8",
  "Yahoo! Finance",
  "Yelp",
  "Yep",
  "YouTube TV",
];
